name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    
    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: ping -c 10 192.168.122.21
